---
defaults:
  install_options: --include-dependencies
gems:
- name: ruby-debug
  version: >= 0.10
- name: rspec
  version: >= 1.1.4
- name: json
  version: >= 1.1.3
- name: prawn
  version: >= 0.2.2